version: "3.7"
services:
  www:
    build: .
    restart: always
    links:
      - db
    networks:
      - default
    volumes:
      - ./:/var/www/html
    ports:
      - "8001:80"
  db:
    image: mysql:8.0.19
    networks:
      - default
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "990:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - mysql-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: test
    ports:
      - "8000:80"
volumes:
  mysql-data:
